
const {chromium}=require("playwright");const fs=require("fs");const assert=require("node:assert/strict");
(async()=>{
 const browser=await chromium.launch({headless:true,args:["--disable-gpu","--autoplay-policy=no-user-gesture-required"]});
 const evidence=[]; const base=process.env.STUDIO_QA_BASE || "http://host.docker.internal:9893";
 const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:"reduce",locale:"en-US"});
 const page=await context.newPage(); const errors=[];page.on("pageerror",e=>errors.push(e.message));
 const fixtureResponse = await page.goto(base+"/",{waitUntil:"networkidle"}); assert.equal(fixtureResponse.headers()["x-aniflive-ui-fixture"],"synthetic","Refusing to run mutations against a real Studio"); await page.locator("body.studio-ux").waitFor();
 assert.equal(await page.locator("#railToggle").count(),0);
 evidence.push("Original dock remains without the unwanted hamburger control");
 await page.locator('#moduleNav [data-view="settings"]').click();
 await page.locator('#workstationSettingsForm').waitFor({state:"visible"});
 const disclosure=page.locator('[data-ux-disclosure="workstationAdvanced"]');
 await disclosure.locator("summary").click();
 assert.equal(await page.locator("#settingsRefreshSeconds").evaluate(e=>getComputedStyle(e).backgroundColor),await page.locator("#settingsDefaultLanguage").evaluate(e=>getComputedStyle(e).backgroundColor),"Advanced fields retain the shared form surface");
 await page.locator("#settingsRefreshSeconds").fill("0");
 await disclosure.locator("summary").click();await page.locator('#workstationSettingsForm button[type="submit"]').click();
 assert.equal(await disclosure.getAttribute("open"),"");assert.equal(await page.locator("#settingsRefreshSeconds").getAttribute("aria-invalid"),"true");
 assert.equal(await page.evaluate(()=>document.activeElement.id),"settingsRefreshSeconds");
 evidence.push("Invalid collapsed advanced field is revealed and focused");
 await page.locator("#settingsRefreshSeconds").fill("7");
 await page.waitForTimeout(5600);
 assert.equal(await page.locator("#settingsRefreshSeconds").inputValue(),"7");
 assert.match(await page.locator("#settingsSaveState").innerText(),/Unsaved/);
 evidence.push("Automatic refresh preserves unsaved settings");
 const patches=[];
 await page.route("**/api/workstation/settings",async route=>{
  if(route.request().method()!=="PATCH")return route.continue();
  const body=route.request().postDataJSON();patches.push(body);
  await new Promise(r=>setTimeout(r,600));
  await route.fulfill({json:{data:body}});
 });
 await page.locator('#workstationSettingsForm button[type="submit"]').dblclick();
 await page.locator("#settingsRefreshSeconds").fill("8");
 await page.waitForTimeout(900);
 assert.equal(patches.length,1);assert.equal(patches[0].auto_refresh_seconds,7);
 assert.equal(await page.locator("#settingsRefreshSeconds").inputValue(),"8");
 assert.match(await page.locator("#settingsSaveState").innerText(),/Unsaved/);
 assert.deepEqual(Object.keys(patches[0]).sort(),["auto_refresh_seconds","default_benchmark_language","default_continuity_policy","default_language","default_training_preset","default_tse_target_threshold","overview_motion"].sort());
 evidence.push("Double save sends once, preserves original API body, and retains edits during save");
 await page.locator(".viewport").evaluate(el=>el.scrollTop=300);
 const before=await page.locator(".viewport").evaluate(el=>el.scrollTop);
 await page.locator('#moduleNav [data-view="jobs"]').click();
 await page.locator('#moduleNav [data-view="settings"]').click();
 await page.waitForTimeout(100);
 assert.ok(Math.abs(await page.locator(".viewport").evaluate(el=>el.scrollTop)-before)<3);
 evidence.push("Returning to a module restores its reading position");
 await page.locator('#moduleNav [data-view="training"]').click();
 await page.locator('[data-view-panel="training"] [data-open-project]').click();
 await page.locator("#projectName").fill("QA draft survives Escape");
 await page.keyboard.press("Escape");await page.locator("#projectDialog").waitFor({state:"hidden"});
 evidence.push("Project dialog closes with Escape");
 await page.locator('#moduleNav [data-view="jobs"]').click();
 await page.locator("#queueJobButton").click();
 await page.locator("#jobDialog").waitFor({state:"visible"});
 await page.keyboard.press("Escape");await page.locator("#jobDialog").waitFor({state:"hidden"});
 evidence.push("Escape on a closed select propagates to close its job dialog");

 await page.locator('#moduleNav [data-view="synthesis"]').click();
 const synth=page.frameLocator("#synthesisFrame");
 await synth.locator("#text").waitFor({state:"visible"});
 await synth.locator("#text").fill("今日はいい天気ですね。");
 await synth.locator('[data-disclosure="generation"] summary').click();
 await synth.locator("#generationTopK").fill("12");
 await synth.locator('[data-disclosure="generation"] summary').click();
 assert.equal(await synth.locator("#generationTopK").inputValue(),"12");
 await synth.locator("#play").click();
 await synth.locator("#downloadAudio:not([disabled])").waitFor({timeout:12000});
 evidence.push("Embedded synthesis retains settings and produces downloadable synthetic QA audio");
 await page.screenshot({path:"/qa/shots/desktop-interaction.png"});
 await context.close();
 const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:"reduce",locale:"zh-TW"});
 const mobile=await phone.newPage();mobile.on("pageerror",e=>errors.push(e.message));
 await mobile.goto(base+"/",{waitUntil:"networkidle"});
 await mobile.locator("#mobileMoreButton").tap();
 await mobile.locator("#mobileNavSheet[open]").waitFor();
 await mobile.locator('#mobileNavSheet [data-view="training"]').tap();
 await mobile.locator('#mobileNavSheet').waitFor({state:"hidden"});
 assert.equal(await mobile.locator(".training-project-workspace").evaluate(el=>el.firstElementChild.classList.contains("domain-main")),true);
 await mobile.locator(".training-project-inspector .ux-project-jump").tap();
 assert.equal(await mobile.evaluate(()=>document.activeElement.classList.contains("domain-main")),true);
 evidence.push("Mobile More navigation and selected-project/list shortcuts remain reachable");
 await mobile.locator('.rail [data-view="synthesis"]').tap();
 const mf=mobile.frameLocator("#synthesisFrame");await mf.locator("#text").fill("手機操作測試。");
 const positions=await mobile.locator("#synthesisFrame").evaluate(frame=>{
  const doc=frame.contentDocument;const play=doc.getElementById("play").getBoundingClientRect();
  const expression=doc.querySelector(".expression-field").getBoundingClientRect();
  return {play:play.top,expression:expression.top,width:doc.documentElement.scrollWidth,viewport:frame.clientWidth};
 });
 assert.ok(positions.play<positions.expression);assert.ok(positions.width<=positions.viewport+1);
 await mf.locator(".ux-synthesis-details").first().locator("summary").tap();
 await mf.locator("#generationSeed").fill("2026");
 await mobile.screenshot({path:"/qa/shots/phone-interaction.png"});
 evidence.push("Mobile synthesis prioritizes playback without removing expression or advanced controls");
 await phone.close();await browser.close();
 assert.deepEqual(errors,[]);
 fs.writeFileSync("/qa/interaction-results.json",JSON.stringify({passed:evidence.length,cases:evidence,errors},null,2));
 console.log(JSON.stringify(evidence,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
