services:
  aniflive-tts:
    build:
      args:
        CUDA_BASE_IMAGE: nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04@sha256:810756cab1c28ce693499a5c2ebb66f6d10a61d026998c8606bad449643a4c49
        TORCH_REQUIREMENTS: requirements/torch-cu121.txt
    image: aniflive-tts:1.0.0-cu121
